Repository opencobra/cobrapy, pull requests merged in 2021-03, with the labels that each got.

#1057 refactor: cobra.sampling.core
  src/cobra/sampling/__init__.py
  src/cobra/sampling/achr.py
  src/cobra/sampling/core.py
  src/cobra/sampling/hr_sampler.py
  src/cobra/sampling/optgp.py
Labels: enhancement, ready

#1063 refactor: remove six usage
  setup.cfg
  src/cobra/core/dictlist.py
  src/cobra/core/group.py
  src/cobra/core/metabolite.py
  src/cobra/core/model.py
  src/cobra/core/object.py
  src/cobra/core/reaction.py
  src/cobra/flux_analysis/fastcc.py
  src/cobra/flux_analysis/phenotype_phase_plane.py
  src/cobra/flux_analysis/reaction.py
  src/cobra/io/dict.py
  src/cobra/io/json.py
  src/cobra/io/mat.py
  src/cobra/io/sbml.py
  src/cobra/io/yaml.py
  src/cobra/manipulation/delete.py
  src/cobra/manipulation/modify.py
  src/cobra/test/test_core/test_core_reaction.py
  src/cobra/test/test_core/test_dictlist.py
  src/cobra/test/test_flux_analysis/test_deletion.py
  src/cobra/test/test_flux_analysis/test_variability.py
  tox.ini
Labels: enhancement, ready

#1065 refactor: multiprocessing.Pool usage
  src/cobra/flux_analysis/deletion.py
  src/cobra/flux_analysis/variability.py
  src/cobra/sampling/optgp.py
Labels: enhancement, ready

#1066 docs: update instruction on running parallel tox tests
  .github/CONTRIBUTING.rst
Labels: docs, ready

#1070 Speed up Windows multiprocessing via file dump
  src/cobra/flux_analysis/deletion.py
  src/cobra/flux_analysis/variability.py
  src/cobra/sampling/optgp.py
  src/cobra/test/test_util/test_process_pool.py
  src/cobra/util/__init__.py
  src/cobra/util/process_pool.py
Labels: enhancement
