Repository opencobra/cobrapy, pull requests merged in 2022-02, with the labels that each got.

#1134 GPR as a new class
  src/cobra/core/__init__.py
  src/cobra/core/gene.py
  src/cobra/core/model.py
  src/cobra/core/reaction.py
  src/cobra/io/sbml.py
  src/cobra/manipulation/__init__.py
  src/cobra/manipulation/delete.py
  src/cobra/manipulation/modify.py
  src/cobra/test/data/iJO1366.pickle
  src/cobra/test/data/mini.json
  src/cobra/test/data/mini.mat
  src/cobra/test/data/mini.pickle
  src/cobra/test/data/mini.yml
  src/cobra/test/data/raven.pickle
  src/cobra/test/data/salmonella.pickle
  src/cobra/test/test_core/test_core_reaction.py
  src/cobra/test/test_core/test_gene.py
  src/cobra/test/test_core/test_gpr.py
  src/cobra/test/test_manipulation/test_delete.py
Labels: WIP

#1152 refactor: cobra.io.yaml
  src/cobra/io/yaml.py
  src/cobra/test/test_io/test_yaml.py
Labels: enhancement, ready

#1153 refactor: cobra.io.mat
  src/cobra/io/mat.py
  src/cobra/test/test_io/test_mat.py
Labels: enhancement
